iridanext {
    enabled = true
    output {
        path = "${params.outdir}/iridanext.output.json.gz"
        overwrite = true
        files {
            global = ["**/multiqc/multiqc_report.html"]
            samples = [
                "**/fastqc/*_1_fastqc.html",
                "**/fastqc/*_2_fastqc.html",
                "**/fastp/*.fastp.html",
                "**/fastp/*.fastp.json"
            ]
        }
    }
}