#!/usr/bin/env python3
"""
Spike a few real-human-derived reads into the tests/data/real/ fixtures, so the
`test_full` profile exercises actual dehosting (not just a 0%-host check).

Inputs (checked in, not regenerated by this script - see README.md for how to
refresh them):
  - reads_src/                 the downloaded+downsampled real SRA reads, unmodified
  - references/human_mt.fasta  the real human mitochondrial genome (rCRS, NC_012920.1)

Output: reads/ - reads_src plus a handful of simulated human-mtDNA-derived reads,
regenerated from scratch each run (so re-running this script is always safe and
never compounds spike-in on top of itself).

Read simulation reuses the same seeded substitution-mutation approach as
tests/data/generate.py (stdlib `random` only, deterministic).

Regenerate with: python3 tests/data/real/spike_human.py
"""

import gzip
import os
import random
import textwrap

SEED = 20260712
RNG = random.Random(SEED)

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_ILLUMINA_DIR = os.path.join(HERE, "reads_src", "illumina")
SRC_NANOPORE_DIR = os.path.join(HERE, "reads_src", "nanopore")
OUT_ILLUMINA_DIR = os.path.join(HERE, "reads", "illumina")
OUT_NANOPORE_DIR = os.path.join(HERE, "reads", "nanopore")
HUMAN_REF = os.path.join(HERE, "references", "human_mt.fasta")

BASES = "ACGT"
COMPLEMENT = str.maketrans("ACGT", "TGCA")

# (sample, n_human_reads_to_add)
ILLUMINA_SAMPLES = [
    ("KPNEUMONIAE_WGS", 25),
    ("ECOLI_WGS", 25),
    ("SARS2_AMPLICON_ILLUMINA", 15),
]
NANOPORE_SAMPLES = [
    ("SARS2_AMPLICON_ONT", 15),
]


def read_fasta(path):
    seq = []
    with open(path) as fh:
        for line in fh:
            if not line.startswith(">"):
                seq.append(line.strip())
    return "".join(seq)


def revcomp(seq):
    return seq.translate(COMPLEMENT)[::-1]


def mutate(seq, rate=0.01):
    """Introduce substitutions at the given per-base rate."""
    out = list(seq)
    for i, b in enumerate(out):
        if RNG.random() < rate:
            out[i] = RNG.choice([x for x in BASES if x != b])
    return "".join(out)


def make_illumina_pair(ref, read_len=150, insert=350):
    start = RNG.randint(0, len(ref) - insert)
    frag = ref[start:start + insert]
    r1 = mutate(frag[:read_len])
    r2 = mutate(revcomp(frag[-read_len:]))
    return r1, r2


def make_ont_read(ref, min_len=800, max_len=3000):
    length = RNG.randint(min_len, max_len)
    start = RNG.randint(0, len(ref) - length)
    return mutate(ref[start:start + length], rate=0.03)  # ONT: higher error


def read_fastq_gz(path):
    records = []
    with gzip.open(path, "rt") as fh:
        while True:
            rid = fh.readline().rstrip("\n")
            if not rid:
                break
            seq = fh.readline().rstrip("\n")
            fh.readline()  # '+' separator
            qual = fh.readline().rstrip("\n")
            records.append((rid[1:], seq, qual))
    return records


def write_fastq_gz(path, records):
    """mtime=0 keeps the gzip byte-identical across runs."""
    payload = "".join(f"@{rid}\n{seq}\n+\n{qual}\n" for rid, seq, qual in records)
    with open(path, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0, compresslevel=9) as gz:
            gz.write(payload.encode())


def main():
    os.makedirs(OUT_ILLUMINA_DIR, exist_ok=True)
    os.makedirs(OUT_NANOPORE_DIR, exist_ok=True)
    human = read_fasta(HUMAN_REF)

    print(f"Spiking human (mitochondrial, NC_012920.1) reads into tests/data/real fixtures (seed={SEED}):")

    for sample, n_human in ILLUMINA_SAMPLES:
        r1 = read_fastq_gz(os.path.join(SRC_ILLUMINA_DIR, f"{sample}_R1.fastq.gz"))
        r2 = read_fastq_gz(os.path.join(SRC_ILLUMINA_DIR, f"{sample}_R2.fastq.gz"))
        for i in range(n_human):
            s1, s2 = make_illumina_pair(human)
            r1.append((f"human_mt_pe_{i}", s1, "I" * len(s1)))
            r2.append((f"human_mt_pe_{i}", s2, "I" * len(s2)))
        write_fastq_gz(os.path.join(OUT_ILLUMINA_DIR, f"{sample}_R1.fastq.gz"), r1)
        write_fastq_gz(os.path.join(OUT_ILLUMINA_DIR, f"{sample}_R2.fastq.gz"), r2)
        print(f"  {sample}: {len(r1) - n_human} source pairs + {n_human} human pairs = {len(r1)} total")

    for sample, n_human in NANOPORE_SAMPLES:
        records = read_fastq_gz(os.path.join(SRC_NANOPORE_DIR, f"{sample}.fastq.gz"))
        for i in range(n_human):
            s = make_ont_read(human)
            records.append((f"human_mt_ont_{i}", s, "5" * len(s)))
        write_fastq_gz(os.path.join(OUT_NANOPORE_DIR, f"{sample}.fastq.gz"), records)
        print(f"  {sample}: {len(records) - n_human} source reads + {n_human} human reads = {len(records)} total")


if __name__ == "__main__":
    main()
